### ISSUE TITLE
iOS renders a black block instead of loader for both custom and predefined presets.

### ISSUE THREAD

**Issue by MortezaT** [NetanelBasal/ngx-content-loader#8]
I Checked the loader on different devices and it works very nice, but on my iPhone 6s it shows a black box instead of desired output

**Comment by NetanelBasal** [comment]
Can you help to debug it, please?

**Comment by MortezaT** [comment]
@NetanelBasal How can I help you with it?

**Comment by GerardoLSJ** [comment]
The solution is to change the HTML like in the original repo : 
  ```jsx
  {/* Opaque color in Safari and iOS */}
  <ContentLoader 
    primaryColor="rgba(0,0,0,0.06)" 
    secondaryColor="rgba(0,0,0,0.12)">
  

  {/* Semi-transparent color in Safari and iOS */}
  <ContentLoader 
    primaryColor="rgb(0,0,0)"
    secondaryColor="rgb(0,0,0)"
    primaryOpacity={0.06}
    secondaryOpacity={0.12}>
  ```

in this linea apparently

https://github.com/NetanelBasal/ngx-content-loader/blob/b71d908e28e3c57c0316c79cea45b0e7aab65d52/src/lib/src/content-loader.component.html#L14

But i haven't try

Here is the original issue and PR

https://github.com/danilowoz/react-content-loader/issues/93

**Comment by NetanelBasal** [comment]
I would love to see PR copy these changes https://github.com/danilowoz/react-content-loader/pull/96/files. Otherwise, I'll do it when I'm available.

**Comment by NetanelBasal** [comment]
fixed in 1.0.3.

**Comment by vinayakpatil** [comment]
![image](https://user-images.githubusercontent.com/3096223/43195770-a643bd88-9023-11e8-8b37-e55eb617aafa.png)

@NetanelBasal this is still reproducible with 1.0.3 in iOS
